// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.2.1";

// src/lib/mcp/tools/get-offering.ts
import { ToolError, defineTool } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z } from "npm:zod@^3.25.76";

// src/data/offerings.ts
var offerings = [
  {
    slug: "revenue-diagnostic",
    no: "01",
    name: "Revenue Diagnostic",
    duration: "2\u20133 weeks",
    summary: "A fast, deep assessment of your revenue engine.",
    includes: [
      "Pipeline quality + coverage analysis",
      "Forecast methodology review",
      "Sales process + inspection gaps",
      "Leadership cadence evaluation"
    ],
    output: "Forecast reality vs. fiction \xB7 Top 3 revenue blockers \xB7 90-day action plan",
    investment: "$15K \u2013 $25K",
    overview: "A focused, two-to-three week diagnostic that gives leadership an unflinching read on the health of your revenue engine. We look at the deals, the data, and the discipline behind them\u2014then tell you what's real and what's not.",
    whoFor: [
      "CEOs and CROs questioning forecast credibility",
      "Boards needing an independent revenue assessment",
      "Leaders preparing for a fundraise or scaling event"
    ],
    process: [
      { phase: "Week 1", detail: "Data pull, deal sampling, and stakeholder interviews across sales, marketing, and finance." },
      { phase: "Week 2", detail: "Pipeline coverage, forecast methodology, and inspection cadence analysis." },
      { phase: "Week 3", detail: "Findings, prioritized blockers, and a 90-day action plan delivered to the executive team." }
    ],
    deliverables: [
      "Forecast credibility scorecard",
      "Top 3 revenue blockers with root cause",
      "90-day action plan with owners and milestones"
    ]
  },
  {
    slug: "forecast-accuracy-sprint",
    no: "02",
    name: "Forecast Accuracy Sprint",
    duration: "6\u20138 weeks",
    summary: "Our core engagement to stabilize revenue predictability.",
    includes: [
      "Deal inspection rigor",
      "Forecast methodology",
      "Pipeline coverage model",
      "Executive operating cadence"
    ],
    output: "Move toward \xB110\u201315% forecast accuracy",
    investment: "$35K \u2013 $75K",
    featured: true,
    overview: "A six-to-eight week sprint to install the inspection rigor, methodology, and cadence required to forecast within \xB110\u201315%. We work alongside your leaders to rebuild the operating system of revenue\u2014deal by deal, week by week.",
    whoFor: [
      "Companies with chronic forecast misses",
      "Leaders ready to install discipline, not dashboards",
      "Teams scaling past $20M ARR"
    ],
    process: [
      { phase: "Weeks 1\u20132", detail: "Baseline current forecast, inspect open pipeline, and align leadership on standards." },
      { phase: "Weeks 3\u20135", detail: "Implement deal inspection rituals, forecast methodology, and pipeline coverage model." },
      { phase: "Weeks 6\u20138", detail: "Operationalize executive cadence and hand off the system to your team." }
    ],
    deliverables: [
      "Forecast methodology and call playbook",
      "Pipeline coverage model and inspection rhythm",
      "Executive operating cadence template",
      "Trained leaders running the system"
    ]
  },
  {
    slug: "revenue-system-build",
    no: "03",
    name: "Revenue System Build",
    duration: "3\u20136 months",
    summary: "A full transformation of your revenue engine.",
    includes: [
      "Scalable sales process",
      "Pipeline generation system",
      "Hiring and role design",
      "Forecast discipline",
      "Leadership coaching"
    ],
    output: "Predictable, scalable revenue",
    investment: "$90K \u2013 $200K+",
    overview: "A three-to-six month transformation of your revenue function\u2014from pipeline generation through forecast discipline. We design, install, and coach the system that turns revenue from a guess into a discipline.",
    whoFor: [
      "Founder-led companies stepping into a real revenue org",
      "Investor-backed businesses preparing for the next leg of growth",
      "CEOs replacing duct-tape with a true operating system"
    ],
    process: [
      { phase: "Month 1", detail: "Diagnose the full engine, design the target operating model, and align the leadership team." },
      { phase: "Months 2\u20134", detail: "Build the sales process, pipeline generation system, hiring plan, and forecast discipline." },
      { phase: "Months 5\u20136", detail: "Coach leaders, embed cadence, and hand off a self-running revenue system." }
    ],
    deliverables: [
      "Documented sales process and stage definitions",
      "Pipeline generation system across sales and marketing",
      "Role design, hiring scorecards, and ramp plans",
      "Forecast and operating cadence",
      "Coached leadership team"
    ]
  }
];

// src/data/peOfferings.ts
var peOfferings = [
  {
    slug: "revenue-architecture-sprint",
    tag: "Pre-investment",
    name: "Revenue Architecture Sprint",
    summary: "For companies you're evaluating before acquisition. Evaluate the quality of the revenue operating system and leave with a value creation blueprint before you close.",
    overview: "A diligence-grade assessment of the target's revenue engine, run during the LOI-to-close window. We pressure-test forecast credibility, pipeline quality, and sales process maturity, then deliver a value creation blueprint with a prioritized 100-day roadmap so the revenue assumptions in the model are something you can defend at IC.",
    whoFor: [
      "PE firms in active diligence on a platform or add-on",
      "Investment teams underwriting a revenue growth thesis",
      "Operating partners stress-testing forecast assumptions before close"
    ],
    whatWeDo: [
      "Forecast accuracy and pipeline coverage analysis",
      "Sales process and revenue qualification review",
      "Identification of investment risks and value creation levers",
      "100-day post-close roadmap aligned to the value creation plan"
    ],
    outcome: "A defensible read on the revenue engine \u2014 and a blueprint for the first 100 days post-close."
  },
  {
    slug: "revenue-diagnostic",
    tag: "Existing portfolio company",
    name: "Revenue Diagnostic",
    summary: "For portfolio companies missing plan or struggling to forecast. Identify what's limiting performance and prioritize the improvement with the greatest impact on enterprise value.",
    overview: "A focused diagnostic of an existing portfolio company's revenue operating system. We evaluate forecast methodology, pipeline quality, sales process maturity, and leadership cadence \u2014 then prioritize the improvements with the greatest impact on enterprise value.",
    whoFor: [
      "Portfolio companies missing plan or with unreliable forecasts",
      "Operating partners preparing for a value creation reset",
      "Boards needing an independent read before a leadership change"
    ],
    whatWeDo: [
      "Forecast credibility and pipeline health assessment",
      "Sales process and operating cadence evaluation",
      "Root-cause analysis of underperformance",
      "Prioritized action plan ranked by impact on enterprise value"
    ],
    outcome: "Clarity on what's limiting performance \u2014 and a prioritized plan to fix it."
  },
  {
    slug: "revenue-system-build",
    tag: "Core engagement",
    name: "Revenue System Build",
    summary: "For companies ready to operationalize growth. Install the people, process, metrics, technology and operating cadence that create predictable revenue.",
    overview: "Our core engagement. We install the full revenue operating system \u2014 forecast methodology, revenue qualification, repeatable sales process, and leadership operating cadence \u2014 turning revenue into a repeatable business capability rather than individual heroics.",
    whoFor: [
      "Portfolio companies in the first 18 months post-close",
      "Businesses scaling past founder-led or operator-led revenue",
      "Companies preparing for a leadership transition or exit process"
    ],
    whatWeDo: [
      "Install forecast methodology with \xB110% accuracy as the benchmark",
      "Implement revenue qualification and pipeline coverage standards",
      "Build a documented, repeatable sales process",
      "Operationalize a weekly and monthly leadership cadence"
    ],
    outcome: "A working revenue operating system the leadership team owns and runs."
  },
  {
    slug: "revenue-bridge",
    tag: "Leadership transition",
    name: "Revenue Bridge",
    summary: "A leadership transition doesn't require a different methodology \u2014 it requires a different starting point.",
    overview: "Whether you're onboarding a new CRO, VP of Sales, GM, or CEO, we install the operating system before or alongside the leadership change so new executives spend their first 90 days executing instead of diagnosing.",
    whoFor: [
      "Portfolio companies in active executive search",
      "Newly hired CROs, VPs of Sales, GMs, or CEOs",
      "Operating partners managing a leadership transition"
    ],
    whatWeDo: [
      "Install the operating system before or alongside the new hire",
      "Document the current state and translate it into an executable plan",
      "Partner with the incoming executive through onboarding",
      "Hand off a system the new leader owns from Day 1"
    ],
    outcome: "New leadership executes from Day 1 instead of spending six months diagnosing."
  },
  {
    slug: "revenue-advisory",
    tag: "Ongoing",
    name: "Revenue Advisory",
    summary: "For portfolio companies committed to continuous improvement. Quarterly strategic oversight to pressure-test forecasts, coach leadership, and optimize the revenue operating system.",
    overview: "Ongoing strategic oversight for companies that have installed the operating system and want outside eyes on it. We partner with operating partners and executive teams on a quarterly basis to review performance, pressure-test forecasts, coach leaders, and evolve the system as the business grows.",
    whoFor: [
      "Revenue System Build alumni",
      "Operating partners who want an independent quarterly read",
      "Executive teams committed to continuous improvement"
    ],
    whatWeDo: [
      "Quarterly performance and forecast reviews",
      "Leadership coaching for the CRO and revenue leadership team",
      "Ongoing optimization of process, cadence, and metrics",
      "Independent perspective for the board and operating partners"
    ],
    outcome: "A revenue operating system that keeps evolving \u2014 with outside eyes on it."
  }
];

// src/lib/mcp/tools/get-offering.ts
var get_offering_default = defineTool({
  name: "get_offering",
  title: "Get offering details",
  description: "Get the full details of one Athena Revenue Partners offering by slug: overview, who it's for, process, deliverables and outcome.",
  inputSchema: {
    slug: z.string().trim().min(1).describe("Offering slug, e.g. 'revenue-diagnostic'."),
    audience: z.enum(["general", "private-equity"]).default("general").describe("Which catalogue the slug belongs to.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug, audience }) => {
    const found = audience === "private-equity" ? peOfferings.find((o) => o.slug === slug) : offerings.find((o) => o.slug === slug);
    if (!found) {
      const available = (audience === "private-equity" ? peOfferings : offerings).map((o) => o.slug).join(", ");
      throw new ToolError(`No offering with slug "${slug}". Available: ${available}`);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(found, null, 2) }],
      structuredContent: { offering: found }
    };
  }
});

// src/lib/mcp/tools/list-offerings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z2 } from "npm:zod@^3.25.76";
var audienceSchema = z2.enum(["all", "general", "private-equity"]);
var list_offerings_default = defineTool2({
  name: "list_offerings",
  title: "List offerings",
  description: "List Athena Revenue Partners' consulting offerings with slug, name, duration and a short summary. Optionally filter by audience.",
  inputSchema: {
    audience: audienceSchema.default("all").describe("Which catalogue to list: 'general', 'private-equity', or 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ audience }) => {
    const general = offerings.map((o) => ({
      audience: "general",
      slug: o.slug,
      name: o.name,
      duration: o.duration,
      summary: o.summary,
      investment: o.investment
    }));
    const pe = peOfferings.map((o) => ({
      audience: "private-equity",
      slug: o.slug,
      name: o.name,
      stage: o.tag,
      summary: o.summary
    }));
    const items = audience === "general" ? general : audience === "private-equity" ? pe : [...general, ...pe];
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/request-diagnostic.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/request-diagnostic.ts
var request_diagnostic_default = defineTool3({
  name: "request_diagnostic",
  title: "Request a revenue diagnostic",
  description: "Submit a diagnostic request to Athena Revenue Partners \u2014 the same enquiry the website's 'Book a diagnostic' form sends. Only submit with the person's explicit consent and their real contact details.",
  inputSchema: {
    name: z3.string().trim().min(1).max(100).describe("Full name of the person requesting."),
    email: z3.string().trim().email().max(255).describe("Business email address."),
    company: z3.string().trim().max(150).optional().describe("Company name."),
    role: z3.string().trim().max(100).optional().describe("Job title, e.g. CEO or CRO."),
    arr_stage: z3.string().trim().max(100).optional().describe("Current ARR or funding stage."),
    challenge: z3.string().trim().max(1e3).optional().describe("The revenue challenge they want help with.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, company, role, arr_stage, challenge }) => {
    const supabase = supabaseAnon();
    const { error } = await supabase.from("diagnostic_requests").insert({
      id: crypto.randomUUID(),
      name,
      email,
      company: company || null,
      role: role || null,
      arr_stage: arr_stage || null,
      challenge: challenge || null
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `Diagnostic request submitted for ${name} (${email}). The Athena team will follow up by email.`
        }
      ]
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "athena-revenue-partners",
  title: "Athena Revenue Partners",
  version: "0.1.0",
  instructions: "Tools for Athena Revenue Partners, a revenue leadership consultancy. Use `list_offerings` to browse the consulting offerings (general and private-equity catalogues), `get_offering` for the full detail of one offering, and `request_diagnostic` to submit a diagnostic enquiry on behalf of someone who has explicitly asked for it.",
  tools: [list_offerings_default, get_offering_default, request_diagnostic_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.2.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
